### ISSUE TITLE
ServiceProvider.MessageProvider.ShowError errors out when trying to run with default hotkeys occupied

### ISSUE THREAD

**Issue by j4nw** [MathewSachin/Captura#121]
If Captura encounters a global hotkey that it wants to use, it tries to show a human-readable error message on startup and carry on - but this is bugged and crashes the application altogether.

Steps to reproduce:
1. Globally occupy a hotkey that Captura uses in config (in my case it was Print Screen taken by OneDrive)
2. Run Captura

Runs without further issues after commenting out the following line:
https://github.com/MathewSachin/Captura/blob/bd529881443405137ecc14177b5be81fa0e675a9/src/Captura.Core/Models/Hotkeys/HotKeyManager.cs#L52

Stack trace:
```
System.InvalidOperationException occurred
  HResult=0x80131509
  Message=Cannot set Owner property to a Window that has not been shown previously.
  Source=PresentationFramework
  StackTrace:
   at System.Windows.Window.set_Owner(Window value)
   at FirstFloor.ModernUI.Windows.Controls.ModernDialog..ctor()
   at Captura.Models.MessageProvider.<>c__DisplayClass0_0.<ShowError>b__0() in D:\Workspace\Hacktoberfest\Captura\src\Captura\Models\MessageProvider.cs:line 15
   at System.Windows.Threading.Dispatcher.Invoke(Action callback, DispatcherPriority priority, CancellationToken cancellationToken, TimeSpan timeout)
   at System.Windows.Threading.Dispatcher.Invoke(Action callback)
   at Captura.Models.MessageProvider.ShowError(String Message) in D:\Workspace\Hacktoberfest\Captura\src\Captura\Models\MessageProvider.cs:line 13
   at Captura.HotKeyManager.Populate() in D:\Workspace\Hacktoberfest\Captura\src\Captura.Core\Models\Hotkeys\HotKeyManager.cs:line 52
   at Captura.HotKeyManager.RegisterAll() in D:\Workspace\Hacktoberfest\Captura\src\Captura.Core\Models\Hotkeys\HotKeyManager.cs:line 20
   at Captura.ViewModels.MainViewModel.Init(Boolean Persist, Boolean Timer, Boolean Remembered, Boolean Hotkeys) in D:\Workspace\Hacktoberfest\Captura\src\Captura.Core\ViewModels\MainViewModel.cs:line 237
   at Captura.MainWindow..ctor() in D:\Workspace\Hacktoberfest\Captura\src\Captura\MainWindow.xaml.cs:line 62
```

**Comment by MathewSachin** [comment]
Did a fix. Please test

**Comment by j4nw** [comment]
All good, cheers!

**Comment by MathewSachin** [comment]
Thank you!
