### ISSUE TITLE
Cannot record region using captura-cli

### ISSUE THREAD

**Issue by jesperll** [MathewSachin/Captura#283]
captura-cli.exe start --source 100,100,300,400
Captura v8.0.0
(c) 2018 Mathew Sachin

Video Buffer Allocated: 0
Press p to pause or resume, q to quit
System.NullReferenceException: Object reference not set to an instance of an object.
   at Captura.ViewModels.RecordingViewModel.<>c__DisplayClass67_0.<StopRecording>b__0()
   at System.Threading.Tasks.Task.InnerInvoke()
   at System.Threading.Tasks.Task.Execute()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Captura.ViewModels.RecordingViewModel.<StopRecording>d__67.MoveNext()

I had a look at the source and it seems to be caused by RegionSourceProvider being initialized by MainViewModel before FakeRegionProvider.SelectedRegion is set thereby recording from 0,0,0,0 instead of the one on the command line

**Comment by MathewSachin** [comment]
Fixed! Thank you for reporting 👍 

Here's a dev build to test: https://ci.appveyor.com/api/buildjobs/w7e0a3whmyqsccio/artifacts/Captura-Portable.zip
