### ISSUE TITLE
This pipe is being closed

### ISSUE THREAD

**Issue by siriuszyx** [MathewSachin/Captura#390]
**Describe the bug**
Cannot record video from the second recording.

**To Reproduce**
1. Install
2. Record first video. Fine.
3. Record second video. This problem occurs.
![image](https://user-images.githubusercontent.com/31344240/55527830-40fb3480-56cd-11e9-84de-188a890f7952.png)

for v8.0.0
```ffmpeg version N-93523-gb131a07e4b Copyright (c) 2000-2019 the FFmpeg developers
  built with gcc 8.2.1 (GCC) 20190212
  configuration: --enable-gpl --enable-version3 --enable-sdl2 --enable-fontconfig --enable-gnutls --enable-iconv --enable-libass --enable-libdav1d --enable-libbluray --enable-libfreetype --enable-libmp3lame --enable-libopencore-amrnb --enable-libopencore-amrwb --enable-libopenjpeg --enable-libopus --enable-libshine --enable-libsnappy --enable-libsoxr --enable-libtheora --enable-libtwolame --enable-libvpx --enable-libwavpack --enable-libwebp --enable-libx264 --enable-libx265 --enable-libxml2 --enable-libzimg --enable-lzma --enable-zlib --enable-gmp --enable-libvidstab --enable-libvorbis --enable-libvo-amrwbenc --enable-libmysofa --enable-libspeex --enable-libxvid --enable-libaom --enable-libmfx --enable-amf --enable-ffnvcodec --enable-cuvid --enable-d3d11va --enable-nvenc --enable-nvdec --enable-dxva2 --enable-avisynth --enable-libopenmpt
  libavutil      56. 26.100 / 56. 26.100
  libavcodec     58. 48.100 / 58. 48.100
  libavformat    58. 26.101 / 58. 26.101
  libavdevice    58.  7.100 / 58.  7.100
  libavfilter     7. 48.100 /  7. 48.100
  libswscale      5.  4.100 /  5.  4.100
  libswresample   3.  4.100 /  3.  4.100
  libpostproc    55.  4.100 / 55.  4.100
\\.\pipe\captura-fdcc0be2-4609-453a-b41d-833d91c4b647: Invalid argument
```

for v9.0.2
```ARGS:
-------------
-thread_queue_size 512 -framerate 15 -f rawvideo -pix_fmt rgb32 -video_size 1920x1080 -i \\.\pipe\captura-b31b3a94-79ac-4570-b8f1-90e7e1b00b32 -thread_queue_size 512 -f s16le -acodec pcm_s16le -ar 44100 -ac 2 -i \\.\pipe\captura-a55a243a-06ad-4580-ba5c-4d6830240975 -r 15 -vcodec libxvid -qscale:v 1 -c:a libmp3lame -qscale:a 0 "C:\Users\Yixuan\Documents\Captura\2019-04-04-11-37-02.avi"

OUTPUT:
-------------
ffmpeg version N-93523-gb131a07e4b Copyright (c) 2000-2019 the FFmpeg developers
  built with gcc 8.2.1 (GCC) 20190212
  configuration: --enable-gpl --enable-version3 --enable-sdl2 --enable-fontconfig --enable-gnutls --enable-iconv --enable-libass --enable-libdav1d --enable-libbluray --enable-libfreetype --enable-libmp3lame --enable-libopencore-amrnb --enable-libopencore-amrwb --enable-libopenjpeg --enable-libopus --enable-libshine --enable-libsnappy --enable-libsoxr --enable-libtheora --enable-libtwolame --enable-libvpx --enable-libwavpack --enable-libwebp --enable-libx264 --enable-libx265 --enable-libxml2 --enable-libzimg --enable-lzma --enable-zlib --enable-gmp --enable-libvidstab --enable-libvorbis --enable-libvo-amrwbenc --enable-libmysofa --enable-libspeex --enable-libxvid --enable-libaom --enable-libmfx --enable-amf --enable-ffnvcodec --enable-cuvid --enable-d3d11va --enable-nvenc --enable-nvdec --enable-dxva2 --enable-avisynth --enable-libopenmpt
  libavutil      56. 26.100 / 56. 26.100
  libavcodec     58. 48.100 / 58. 48.100
  libavformat    58. 26.101 / 58. 26.101
  libavdevice    58.  7.100 / 58.  7.100
  libavfilter     7. 48.100 /  7. 48.100
  libswscale      5.  4.100 /  5.  4.100
  libswresample   3.  4.100 /  3.  4.100
  libpostproc    55.  4.100 / 55.  4.100
\\.\pipe\captura-b31b3a94-79ac-4570-b8f1-90e7e1b00b32: Invalid argument
```

When I try to reinstall ffmpeg.exe:

```System.ObjectDisposedException: The CancellationTokenSource has been disposed.
   at System.Threading.CancellationTokenSource.ThrowObjectDisposedException()
   at Captura.ViewModels.FFmpegDownloadViewModel.<Cancel>d__38.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Captura.Views.FFmpegDownloaderWindow.<>c__DisplayClass0_0.<<-ctor>b__0>d.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.AsyncMethodBuilderCore.<>c.<ThrowAsync>b__6_0(Object state)
   at System.Windows.Threading.ExceptionWrapper.InternalRealCall(Delegate callback, Object args, Int32 numArgs)
   at System.Windows.Threading.ExceptionWrapper.TryCatchWhen(Object source, Delegate callback, Object args, Int32 numArgs, Delegate catchHandler)```
```

**Desktop (please complete the following information):**
 - OS: Windows 10 Home 1809
 - RAM: 8GB*2 2666MHz
 - CPU: i7-8750H
 - Graphic Card: GTX 1060 Max-Q
 - Version: v8.0.0 and v9.0.2

**Comment by hachi1030-Allen** [comment]
I seem to have the same issue. But even on the first recording. Today I recorded once, and got the issue after about 1 hour and 15 minutes.

Why this is still so many bugs?

I might have to switch a tool.

**Comment by MathewSachin** [comment]
@hachi1030-Allen
I think this issue is different from what you're experiencing.
In this issue, error occurs when recording starts, in your case it happened after 1 hour 15 minutes.
In your case it might be happening due to the large region size (as mentioned in #401).

Captura is not currently optimized for recording large displays.

For now, you will have to switch to a different tool for recording large displays.

**Comment by allenliu1030** [comment]
Hi @MathewSachin 

No, today when the issue happened, I was recording on a screen which is 1920x1080.

Not a large screen.

Thanks.

**Comment by MathewSachin** [comment]
If this issue still happens, use `SharpAvi` or `Media Foundation` (available in latest Beta) writers instead of `FFmpeg`.

I'm closing this issue for now, going forward Media Foundation writer will be the default instead of FFmpeg.
