### ISSUE TITLE
win10 19h1

### ISSUE THREAD

**Issue by iamsunxing** [MathewSachin/Captura#419]
1.I download the Captura v9.0.0-beta3.1 portable version. 
2.Select a screen(total double), and choose MF encoder.
3.It occured when I click the "start record button". 
By the way, I use the win10 19H1.
The error is below(My system language is Chinese, so part error is showed in Chinese.):

SharpDX.SharpDXException: HRESULT: [0x8899000C], Module: [SharpDX.Direct2D1], ApiCode: [D2DERR_RECREATE_TARGET/RecreateTarget], Message: 存在可以恢复的演示错误。调用方需要重新创建、重新渲染整个帧，并重新尝试显示。

   at SharpDX.Result.CheckError()
   at DesktopDuplication.Direct2DEditorSession.EndDraw()
   at DesktopDuplication.Direct2DEditor.GenerateFrame()
   at Screna.Recorder.<>c__DisplayClass14_0.<DoRecord>b__2()
   at System.Threading.Tasks.Task`1.InnerInvoke()
   at System.Threading.Tasks.Task.Execute()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Screna.Recorder.<DoRecord>d__14.MoveNext()

**Comment by MathewSachin** [comment]
What are your CPU and GPU specifications?

**Comment by iamsunxing** [comment]
i5-4200u 
GPU 0
	Intel(R) HD Graphics Family
GPU 1
	AMD Radeon HD 8670M

**Comment by YamaJP** [comment]
Good afternoon! Any tips or solutions to the situation?

Thanks!

**Comment by MathewSachin** [comment]
I've not narrowed down exactly what is causing this issue.
It will be really helpful if you could provide information on which CPU+GPU the error occurred and on which it worked fine.

**Comment by YamaJP** [comment]
Thanks for responding so promptly!
To be honest, using only Intel CPUs and Intel GPUs or NVidia I had problems. Usually this occurs when I record several times in a sequence, for example, I make six recordings OK and the situation occurs in the seventh. This is very variable, there are times when I can make ten recordings without problems.
