### ISSUE TITLE
Problem with capturin second monitor

### ISSUE THREAD

**Issue by IanGraham** [MathewSachin/Captura#427]
I have display of my laptop and DELL display. When i try to capture image fro laptop display all works fine, but when i try to capture image from DELL display something goes wrong.

![1](https://user-images.githubusercontent.com/2924135/60089767-d5fc4f80-9749-11e9-8cc4-85f39ca4c4da.JPG)
![2](https://user-images.githubusercontent.com/2924135/60089768-d5fc4f80-9749-11e9-8daf-03dc17a9d5af.JPG)

**Comment by MathewSachin** [comment]
Does this happen in the latest beta?

Here's the link to the beta version: https://github.com/MathewSachin/Captura/releases/download/v9.0.0-beta3.1/Captura-Portable.zip

**Comment by IanGraham** [comment]
On the ltest beta that you linked there is the same problem, but added this one: SharpDX.SharpDXException: HRESULT: [0x8899000C], Module: [SharpDX.Direct2D1], ApiCode: [D2DERR_RECREATE_TARGET/RecreateTarget], Message: Произошла ошибка представления, которая, возможно, исправима. Вызывающий объект должен повторно создать и прорисовать весь кадр, а затем повторить попытку представления.

   at SharpDX.Result.CheckError()
   at DesktopDuplication.Direct2DEditorSession.EndDraw()
   at DesktopDuplication.Direct2DEditor.GenerateFrame()
   at Screna.Recorder.<>c__DisplayClass14_0.<DoRecord>b__2()
   at System.Threading.Tasks.Task`1.InnerInvoke()
   at System.Threading.Tasks.Task.Execute()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Screna.Recorder.<DoRecord>d__14.MoveNext

When i try to select a display to use i see this picture:
![2019-06-25_13-18-27](https://user-images.githubusercontent.com/2924135/60090868-01803980-974c-11e9-8692-705cb98f80e8.png)

As i think Captura try to capture this kind of third monitor in the middle.

**Comment by docfallingapart** [comment]
I'm seeing this same error with 9.0.0-beta3.1 when doing "Full Screen" or "Screen".  "Area" and "Window" both work ok.  This error happens with all Encoders.  No problem with 8.0.

My system:
Windows 10 Pro, 1903, 18362.295
Intel i7-4790
Gigabyte z97X-UD5H mainboard
GeForce GTX 1060 6GB, Driver 431.70
Two monitors

**Comment by Wenzy--** [comment]
I have the similar issue. I have tried Captura v9.0.0-beta3.1.I use a laptop 1920 * 1080 and a 4k monitor.When i record in the monitor, the capture area will always has an offset
