### ISSUE TITLE
Video Quality video and Color Change

### ISSUE THREAD

**Issue by akcansoft** [MathewSachin/Captura#491]
Firstly thanks for this program.
I record the screen with 100% quality setting, but the video quality decreases and the colors change.
![captura](https://user-images.githubusercontent.com/7031346/74935289-0db2b880-53f9-11ea-8f8e-89504d0a2447.png)
Captura v8.0.0
Windows 10 TR x64
Intel i5 760
AMD Radeon HD 6870
4 GB DDR3 Ram
ffmpeg version git-2020-02-11-f15007a
![VideoFrame](https://user-images.githubusercontent.com/7031346/74935315-1905e400-53f9-11ea-8769-2304017ace7e.png)

**Comment by yumetodo** [comment]
Color space(YUV BT.601, YUV BT.709, etc) difference between source image and Video Frame Decode image is suspicious, I think.

**Comment by akcansoft** [comment]
I downloaded and installed **Lagarith Lossless Video Codec** from https://lags.leetcode.net/codec.html 

I recorded test video with Captura v8.0.0 **SharpAvi / Lagarith**.
Test is **OK**. The recording quality is better and the color change is less.
But when I try to record with **Captura v9.0.0-beta4** with Lagarith codec, an error occurs.

**An Error Occured:**
Error calling wrapped encoder.
> Captura v0.0.3502.0
OS: Microsoft Windows 10 Home Single Language|C
64-bit OS
64-bit Process
4 processor(s)
Name: Intel(R) Core(TM) i5 CPU         760  @ 2.80GHz
NumberOfCores: 4
NumberOfLogicalProcessors: 4
Name: Fiziksel Bellek
Capacity: 4294967296
Name: AMD Radeon HD 6800 Series
AdapterRAM: 1073741824
Desktop: {X=0,Y=0,Width=1920,Height=1080}
Screen: \\.\DISPLAY1: {X=0,Y=0,Width=1920,Height=1080}
Mic: Mikrofon (Realtek High Definition Audio)
Speaker: Hoparlör (Realtek High Definition Audio)
System.Reflection.TargetInvocationException: Error calling wrapped encoder. ---> System.InvalidOperationException: No compatible MPEG-4 encoder found.
   at SharpAvi.Codecs.Mpeg4VideoEncoderVcm..ctor(Int32 width, Int32 height, Double fps, Int32 frameCount, Int32 quality, FourCC[] codecPreference)
   at SharpAvi.Codecs.EncodingStreamFactory.<>c__DisplayClass2_0.<AddMpeg4VideoStream>b__0()
   at SharpAvi.Codecs.SingleThreadedVideoEncoderWrapper.<>c__DisplayClass15_0`1.<DispatcherInvokeAndPropagateException>b__0()
   --- End of inner exception stack trace ---
   at SharpAvi.Codecs.SingleThreadedVideoEncoderWrapper.WrapAndRethrowException(Exception wrappedException)
   at SharpAvi.Codecs.SingleThreadedVideoEncoderWrapper.DispatcherInvokeAndPropagateException[TResult](Func`1 func)
   at SharpAvi.Codecs.SingleThreadedVideoEncoderWrapper..ctor(Func`1 encoderFactory)
   at SharpAvi.Codecs.EncodingStreamFactory.AddMpeg4VideoStream(AviWriter writer, Int32 width, Int32 height, Double fps, Int32 frameCount, Int32 quality, Nullable`1 codec, Boolean forceSingleThreadedAccess)
   at Captura.Models.AviWriter.CreateVideoStream(Int32 Width, Int32 Height)
   at Captura.Models.AviWriter..ctor(String FileName, AviCodec Codec, IImageProvider ImageProvider, Int32 FrameRate, IAudioProvider AudioProvider)
   at Captura.Models.SharpAviItem.GetVideoFileWriter(VideoWriterArgs Args)
   at Captura.ViewModels.RecordingModel.GetVideoFileWriterWithPreview(IImageProvider ImgProvider, IAudioProvider AudioProvider, RecordingModelParams RecordingParams)
   at Captura.ViewModels.RecordingModel.SetupVideoRecorder(IAudioProvider AudioProvider, RecordingModelParams RecordingParams, IMouseKeyHook MouseKeyHook)

**View Details**
>System. Reflection. TargetlnvocationException
**Message**
Error calling wrapped encoder.
**Stack Trace**
at SharpAvi.CodecsSingIeThreadedVideoEncoderWrapper.WrapAndRethrowException(Exception wrappedException)
at func)
at SharpAvi.Codecs.SingIeThreadedVideoEncoderWrapper..ctor(Func'I encoderFactory)
at SharpAvi.Codecs.EncodingStreamFactory.AddMpeg4VideoStream(AviWriter writer, Int32 width, Int32 height Double fps Int32 frameCount, Int32 quality, Nullable•l codec Boolean forceSingIeThreadedAccess)
at Captura.ModeIs.AviWriter.CreateVideoStream(Int32 Width, Int32 Height)
at Captura.ModeIs.AviWriter..ctor(String FileName, AviCodec Codec Ilmageprovider Imageprcwider, Int32 FrameRate, IAudioProvider AudioProvider)
at Captura. Models.SharpAviItem .GetVideoFiIeWriter(VideoWriterArgs Args)
at Captura.ViewModeIs.RecordingModeI.GetVideoFiIeWriterWithPreview(IImageProvider ImgProvider, IAudioProvider AudioProvider, RecordingModeIParams Recordingparams)
at Captura.ViewModeIs.RecordingModeISetupVideoRecorder(IAudioProvider AudioProvider, RecordingModeIParams Recordingparams, IMouseKeyHook MouseKeyHook)
**Target Site**
Void WrapAndRethrowException(System.Exception)
**Source**
SharpAvi
**HResuIt**
-2146232828

**Comment by SadPencil** [comment]
@akcansoft Set the color space to `rgb24` solves this problem. YUV color space is not suitable for capturing screen.
You can download a modified version of Captura v8.0.0 with only `rgb24` color space is added.
https://github.com/SadPencil/Captura/releases/tag/v8.0.0-mod

**Comment by yumetodo** [comment]
@SadPencil Do you have a plan to create PR?

**Comment by SadPencil** [comment]
> 
> 
> @SadPencil Do you have a plan to create PR?

I can't. This modification only works on release-v8.0.0, not on the latest master branch.
