### ISSUE TITLE
An error occurred

### ISSUE THREAD

**Issue by neatgz** [MathewSachin/Captura#492]
**Describe the bug**
Click the 'Record' button, an error message appeared. It says 'SharpDX.SharpDXException: HRESULT: [0x8899000C], Module: [SharpDX.Direct2D1], ApiCode: [D2DERR_RECREATE_TARGET/RecreateTarget], '

**To Reproduce**
1. Captura-Portable v9.0.0-beta3.1
2. Open 'captura.exe'
3. Click the 'Record' button, an error message appeared.

**Screenshots**

**Desktop (please complete the following information):**
 - OS: [tested on both windows 10 1909 x64 and windows 10 1809 ltsc x64]
 - RAM: [16GB]
 - CPU: [ i7-4700HQ ]
 - Graphic Card:  No discrete graphics,  Intel(R) Iris(TM) Pro Graphics 5200
 - Captura Version: [ v9.0.0-beta3.1 , tested v8.0.0 works fine ]

**Additional context**
Thanks a lot !

**Comment by saberbin** [comment]
SharpDX.SharpDXException: HRESULT: [0x8899000C], Module: [SharpDX.Direct2D1], ApiCode: [D2DERR_RECREATE_TARGET/RecreateTarget], Message: 存在可以恢复的演示错误。调用方需要重新创建、重新渲染整个帧，并重新尝试显示。

   at SharpDX.Result.CheckError()
   at DesktopDuplication.Direct2DEditorSession.EndDraw()
   at DesktopDuplication.Direct2DEditor.GenerateFrame()
   at Screna.Recorder.<>c__DisplayClass14_0.<DoRecord>b__2()
   at System.Threading.Tasks.Task`1.InnerInvoke()
   at System.Threading.Tasks.Task.Execute()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Screna.Recorder.<DoRecord>d__14.MoveNext()

**Comment by ldh999** [comment]
Try change the mouse cursor to default in WIN 10.

**Comment by MathewSachin** [comment]
@ldh999 Can you provide me with a cursor for which recording fails.
I really want to fix this issue but have no other leads right now.

**Comment by neatgz** [comment]
My win 10 was newly installed, I did not change any mouse cursor settings.
my dpi was 200%, maybe it is the reason?
my graphics driver was the newest.
![批注 2020-02-24 094906](https://user-images.githubusercontent.com/22790906/75124622-7943a100-56eb-11ea-9aa3-e01019576aed.png)

**Comment by Yugikira** [comment]
My friends and I encountered similar issue.
Here is my case and solution.
I use ffmpeg to record while I download ffmpeg from its official site instead using the download function integerated in Caputra.
The same warning came out.
After I add the ffmpeg.exe to the environment path, the issue gone.

**Comment by cmmei** [comment]
I happened the same error in Win10.

**Comment by MathewSachin** [comment]
Does anyone get this error on 1080p or lesser resolutions?
I've only gotten reports of this error happening on larger screens.

If this is true, or even not, I think I should scale down the video to 1080p by default.
1080p is most probable to have hardware encoders available on every system.
