### ISSUE TITLE
video size is zoomed

### ISSUE THREAD

**Issue by g8up** [MathewSachin/Captura#495]
**Describe the bug**
The size of my recorded video is zoomed, and the cursor was appears chaos.

**To Reproduce**
1. select display 1
2. Click on 'record'
3. preview recorded video

**Expected behavior**
the video size is fill the full player screen when I set the player 1:1 .

**Screenshots**
- video size

![image](https://user-images.githubusercontent.com/8005686/76167791-53ff6a00-61a4-11ea-8a79-74da506bfaa6.png)
- displayer setting in Win10 ( displayer 2 is captured in the video above)
> extend displayer
![image](https://user-images.githubusercontent.com/8005686/76167810-8315db80-61a4-11ea-853a-b2db7143b08f.png)
> master displayer
![image](https://user-images.githubusercontent.com/8005686/76167818-8dd07080-61a4-11ea-8304-24870ff223c3.png)

**Desktop (please complete the following information):**
 - OS: Windows 10
 - RAM: 16GB
 - CPU: intel
 - Graphic Card: GTX960
 - Captura Version: [e.g. v8.0.0]

**Comment by MathewSachin** [comment]
Can you check with v9.0.0-beta4

Here's the download link: https://github.com/MathewSachin/Captura/releases/download/v9.0.0-beta4/Captura-Portable.zip

**Comment by g8up** [comment]
I update to v9.0.0-beta4 （ .Net 4.7.2 installed).

First I select a screen :
<img width="439" alt="22-31-10" src="https://user-images.githubusercontent.com/8005686/78570079-10595800-7857-11ea-9e86-7f80bf0a0478.png">

When I start record , it comes an error:
```
Captura v9.0.0.0
OS: Microsoft Windows 10 专业版|C
64-bit OS
64-bit Process
8 processor(s)

Name: Intel(R) Xeon(R) CPU E3-1231 v3 @ 3.40GHz
NumberOfCores: 4
NumberOfLogicalProcessors: 8

Name: 物理内存
Capacity: 8589934592

Name: 物理内存
Capacity: 8589934592

Name: NVIDIA GeForce GTX 960
AdapterRAM: 2147483648

Desktop: {X=-1620,Y=0,Width=5460,Height=3260}
Screen: \\.\DISPLAY1: {X=-1620,Y=380,Width=1620,Height=2880}
Screen: \\.\DISPLAY2: {X=0,Y=0,Width=3840,Height=2160}
Mic: 麦克风 (USB PnP Sound Device)
Mic: 麦克风 (Yeti Stereo Microphone)
Speaker: 扬声器 (Yeti Stereo Microphone)
Speaker: 扬声器 (USB PnP Sound Device)
Speaker: 扬声器 (Realtek High Definition Audio)
Speaker: LG HDR 4K (NVIDIA High Definition Audio)
Speaker: LG IPS FULLHD (NVIDIA High Definition Audio)
Speaker: Realtek Digital Output(Optical) (Realtek High Definition Audio)
Speaker: Realtek Digital Output (Realtek High Definition Audio)


SharpDX.SharpDXException: HRESULT: [0x8899000C], Module: [SharpDX.Direct2D1], ApiCode: [D2DERR_RECREATE_TARGET/RecreateTarget], Message: 存在可以恢复的演示错误。调用方需要重新创建、重新渲染整个帧，并重新尝试显示。

   at SharpDX.Result.CheckError()
   at DesktopDuplication.Direct2DEditorSession.EndDraw()
   at DesktopDuplication.Direct2DEditor.GenerateFrame(TimeSpan Timestamp)
   at Screna.Recorder.FrameWriter(TimeSpan Timestamp)
   at System.Threading.Tasks.Task`1.InnerInvoke()
   at System.Threading.Tasks.Task.Execute()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Screna.Recorder.<Dispose>d__25.MoveNext()
```

**Comment by MathewSachin** [comment]
Ok. I think I understand the problem now.
One of your screens is rotated and both are at different DPI scaling. I'll try working with a similar setup and see what can be done.
