### ISSUE TITLE
Error on starting to record with FFMPEG

### ISSUE THREAD

**Issue by keilerse** [MathewSachin/Captura#500]
As soon as I start to record the program throws an error (see below). I simply do not know where to start debugging:

> 
> System.IO.IOException: Die Pipe wird gerade geschlossen.
> 
>    at System.IO.__Error.WinIOError(Int32 errorCode, String maybeFullPath)
>    at System.IO.Pipes.NamedPipeServerStream.BeginWaitForConnection(AsyncCallback callback, Object state)
>    at Captura.FFmpegService.WaitForConnection(NamedPipeServerStream ServerStream, Int32 Timeout)
>    at Captura.Models.FFmpegWriter.WriteFrame(IBitmapFrame Frame)
>    at Captura.Models.WithPreviewWriter.WriteFrame(IBitmapFrame Image)
>    at Screna.Recorder.DoWrite()

**Comment by MathewSachin** [comment]
Please provide the following info:

 - OS: [e.g. Windows 8.1]
 - RAM: [e.g. 4GB]
 - CPU: [e.g. i5 2GHz]
 - Graphic Card:
 - Captura Version: [e.g. v8.0.0]

**Comment by keilerse** [comment]
Thank you for your response:

    OS: Windows 10 pro
    RAM: 16 GB
    CPU: AMD Ryzen 7 3700 U
    Graphic Card: Radeon Vega Mobile Gfx 2.3 GHz
    Captura Version: v8.0.0

**Comment by MathewSachin** [comment]
Did you try the latest beta? 9.0.0-beta4
