### ISSUE TITLE
exception 

### ISSUE THREAD

**Issue by LxLi** [MathewSachin/Captura#503]
SharpDX.SharpDXException: HRESULT: [0x8899000C], Module: [SharpDX.Direct2D1], ApiCode: [D2DERR_RECREATE_TARGET/RecreateTarget], Message: 存在可以恢复的演示错误。调用方需要重新创建、重新渲染整个帧，并重新尝试显示。

   at SharpDX.Result.CheckError()
   at DesktopDuplication.Direct2DEditorSession.EndDraw()
   at DesktopDuplication.Direct2DEditor.GenerateFrame()
   at Screna.Recorder.<>c__DisplayClass14_0.<DoRecord>b__2()
   at System.Threading.Tasks.Task`1.InnerInvoke()
   at System.Threading.Tasks.Task.Execute()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Screna.Recorder.<DoRecord>d__14.MoveNext()

**Comment by MathewSachin** [comment]
What are your screen sizes?

**Comment by MathewSachin** [comment]
I still don't have a solution for this but I'm closing this due to no response.
If you have anything to add, comment on #492 which is pretty much the same issue.
