### ISSUE TITLE
an error occured. captura v9.0.0.beta4

### ISSUE THREAD

**Issue by akcansoft** [MathewSachin/Captura#507]
![21-34-59](https://user-images.githubusercontent.com/7031346/77683772-f5126100-6fa9-11ea-86f9-1201601872b5.png)

**Describe the bug**
Full screen record error

**To Reproduce**
1. click Full Screen
2. record button

**Desktop (please complete the following information):**
 - OS: Win 10 x64 SL TR
 - RAM: 4GB
 - CPU: i5-760 2.80 Ghz
 - Graphic Card: Amd Radeon HD 6870
 - Captura Version: 9.0.0.beta4

**Additional context**
`Captura v9.0.0.0
OS: Microsoft Windows 10 Home Single Language|C
64-bit OS
64-bit Process
4 processor(s)

Name: Intel(R) Core(TM) i5 CPU         760  @ 2.80GHz
NumberOfCores: 4
NumberOfLogicalProcessors: 4

Name: Fiziksel Bellek
Capacity: 4294967296

Name: AMD Radeon HD 6800 Series
AdapterRAM: 1073741824

Desktop: {X=0,Y=0,Width=1920,Height=1080}
Screen: \\.\DISPLAY1: {X=0,Y=0,Width=1920,Height=1080}
Mic: Mikrofon (Realtek High Definition Audio)
Speaker: Hoparlör (Realtek High Definition Audio)

View Details:

`Captura v9.0.0.0
OS: Microsoft Windows 10 Home Single Language|C
64-bit OS
64-bit Process
4 processor(s)

Name: Intel(R) Core(TM) i5 CPU         760  @ 2.80GHz
NumberOfCores: 4
NumberOfLogicalProcessors: 4

Name: Fiziksel Bellek
Capacity: 4294967296

Name: AMD Radeon HD 6800 Series
AdapterRAM: 1073741824

Desktop: {X=0,Y=0,Width=1920,Height=1080}
Screen: \\.\DISPLAY1: {X=0,Y=0,Width=1920,Height=1080}
Mic: Mikrofon (Realtek High Definition Audio)
Speaker: Hoparlör (Realtek High Definition Audio)

SharpDX.SharpDXException: HRESULT: [0x8899000C], Module: [SharpDX.Direct2D1], ApiCode: [D2DERR_RECREATE_TARGET/RecreateTarget], Message: Kurtarılabilir bir sunu hatası oldu. Çağıranın çerçevenin tümünü yeniden oluşturması, yeniden işlemesi ve sunuyu yeniden denemesi gerekir.

   at SharpDX.Result.CheckError()
   at DesktopDuplication.Direct2DEditorSession.EndDraw()
   at DesktopDuplication.Direct2DEditor.GenerateFrame(TimeSpan Timestamp)
   at Screna.Recorder.FrameWriter(TimeSpan Timestamp)
   at System.Threading.Tasks.Task`1.InnerInvoke()
   at System.Threading.Tasks.Task.Execute()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Screna.Recorder.<Dispose>d__25.MoveNext()`

SharpDX.SharpDXException: HRESULT: [0x8899000C], Module: [SharpDX.Direct2D1], ApiCode: [D2DERR_RECREATE_TARGET/RecreateTarget], Message: Kurtarılabilir bir sunu hatası oldu. Çağıranın çerçevenin tümünü yeniden oluşturması, yeniden işlemesi ve sunuyu yeniden denemesi gerekir.

   at SharpDX.Result.CheckError()
   at DesktopDuplication.Direct2DEditorSession.EndDraw()
   at DesktopDuplication.Direct2DEditor.GenerateFrame(TimeSpan Timestamp)
   at Screna.Recorder.FrameWriter(TimeSpan Timestamp)
   at System.Threading.Tasks.Task`1.InnerInvoke()
   at System.Threading.Tasks.Task.Execute()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Screna.Recorder.<Dispose>d__25.MoveNext()`

FFMPeg Log:

`ARGS:
-------------
-thread_queue_size 512 -framerate 20 -f rawvideo -pix_fmt nv12 -video_size 1920x1080 -i \\.\pipe\captura-70059d04-1224-48a7-a91b-1979060f84b8 -thread_queue_size 512 -f s16le -acodec pcm_s16le -ar 44100 -ac 2 -i \\.\pipe\captura-9b9f8303-fc95-420a-b9c3-89f6ba99b98e -r 20 -vcodec libx264 -crf 12 -pix_fmt yuv420p -preset ultrafast -c:a aac -strict -2 -b:a 384k "C:\Users\mesut\Documents\Captura\2020-03-26/21-25-37.mp4"

OUTPUT:
-------------
ffmpeg version git-2020-03-24-e5d25d1 Copyright (c) 2000-2020 the FFmpeg developers
  built with gcc 9.2.1 (GCC) 20200122
  configuration: --enable-gpl --enable-version3 --enable-sdl2 --enable-fontconfig --enable-gnutls --enable-iconv --enable-libass --enable-libdav1d --enable-libbluray --enable-libfreetype --enable-libmp3lame --enable-libopencore-amrnb --enable-libopencore-amrwb --enable-libopenjpeg --enable-libopus --enable-libshine --enable-libsnappy --enable-libsoxr --enable-libsrt --enable-libtheora --enable-libtwolame --enable-libvpx --enable-libwavpack --enable-libwebp --enable-libx264 --enable-libx265 --enable-libxml2 --enable-libzimg --enable-lzma --enable-zlib --enable-gmp --enable-libvidstab --enable-libvorbis --enable-libvo-amrwbenc --enable-libmysofa --enable-libspeex --enable-libxvid --enable-libaom --enable-libmfx --enable-ffnvcodec --enable-cuda-llvm --enable-cuvid --enable-d3d11va --enable-nvenc --enable-nvdec --enable-dxva2 --enable-avisynth --enable-libopenmpt --enable-amf
  libavutil      56. 42.101 / 56. 42.101
  libavcodec     58. 76.100 / 58. 76.100
  libavformat    58. 42.100 / 58. 42.100
  libavdevice    58.  9.103 / 58.  9.103
  libavfilter     7. 77.100 /  7. 77.100
  libswscale      5.  6.101 /  5.  6.101
  libswresample   3.  6.100 /  3.  6.100
  libpostproc    55.  6.100 / 55.  6.100
Input #0, rawvideo, from '\\.\pipe\captura-70059d04-1224-48a7-a91b-1979060f84b8':
  Duration: N/A, start: 0.000000, bitrate: 497664 kb/s
    Stream #0:0: Video: rawvideo (NV12 / 0x3231564E), nv12, 1920x1080, 497664 kb/s, 20 tbr, 20 tbn, 20 tbc
Guessed Channel Layout for Input Stream #1.0 : stereo
Input #1, s16le, from '\\.\pipe\captura-9b9f8303-fc95-420a-b9c3-89f6ba99b98e':
  Duration: N/A, bitrate: 1411 kb/s
    Stream #1:0: Audio: pcm_s16le, 44100 Hz, stereo, s16, 1411 kb/s
Stream mapping:
  Stream #0:0 -> #0:0 (rawvideo (native) -> h264 (libx264))
  Stream #1:0 -> #0:1 (pcm_s16le (native) -> aac (native))
Press [q] to stop, [?] for help
[libx264 @ 0000021c4040f500] using cpu capabilities: MMX2 SSE2Fast SSSE3 SSE4.2
[libx264 @ 0000021c4040f500] profile Constrained Baseline, level 4.0, 4:2:0, 8-bit
[libx264 @ 0000021c4040f500] 264 - core 159 - H.264/MPEG-4 AVC codec - Copyleft 2003-2019 - http://www.videolan.org/x264.html - options: cabac=0 ref=1 deblock=0:0:0 analyse=0:0 me=dia subme=0 psy=1 psy_rd=1.00:0.00 mixed_ref=0 me_range=16 chroma_me=1 trellis=0 8x8dct=0 cqm=0 deadzone=21,11 fast_pskip=1 chroma_qp_offset=0 threads=6 lookahead_threads=1 sliced_threads=0 nr=0 decimate=1 interlaced=0 bluray_compat=0 constrained_intra=0 bframes=0 weightp=0 keyint=250 keyint_min=20 scenecut=0 intra_refresh=0 rc=crf mbtree=0 crf=12.0 qcomp=0.60 qpmin=0 qpmax=69 qpstep=4 ip_ratio=1.40 aq=0
Output #0, mp4, to 'C:\Users\mesut\Documents\Captura\2020-03-26/21-25-37.mp4':
  Metadata:
    encoder         : Lavf58.42.100
    Stream #0:0: Video: h264 (libx264) (avc1 / 0x31637661), yuv420p(progressive), 1920x1080, q=-1--1, 20 fps, 10240 tbn, 20 tbc
    Metadata:
      encoder         : Lavc58.76.100 libx264
    Side data:
      cpb: bitrate max/min/avg: 0/0/0 buffer size: 0 vbv_delay: N/A
    Stream #0:1: Audio: aac (LC) (mp4a / 0x6134706D), 44100 Hz, stereo, fltp, 384 kb/s
    Metadata:
      encoder         : Lavc58.76.100 aac
frame=    2 fps=0.0 q=-1.0 Lsize=       7kB time=00:00:00.05 bitrate=1211.4kbits/s speed=1.36x    
video:7kB audio:0kB subtitle:0kB other streams:0kB global headers:0kB muxing overhead: 12.218935%
[libx264 @ 0000021c4040f500] frame I:1     Avg QP: 9.00  size:  6163
[libx264 @ 0000021c4040f500] frame P:1     Avg QP: 2.00  size:    12
[libx264 @ 0000021c4040f500] mb I  I16..4: 100.0%  0.0%  0.0%
[libx264 @ 0000021c4040f500] mb P  I16..4:  0.0%  0.0%  0.0%  P16..4:  0.0%  0.0%  0.0%  0.0%  0.0%    skip:100.0%
[libx264 @ 0000021c4040f500] coded y,uvDC,uvAC intra: 0.0% 0.0% 0.0% inter: 0.0% 0.0% 0.0%
[libx264 @ 0000021c4040f500] i16 v,h,dc,p: 99%  0%  1%  0%
[libx264 @ 0000021c4040f500] i8c dc,h,v,p: 100%  0%  0%  0%
[libx264 @ 0000021c4040f500] kb/s:494.00
[aac @ 0000021c40411480] Qavg: nan
`

**Comment by MathewSachin** [comment]
As a temporary workaround, try enabling `Use GDI instead of Desktop Duplication` on video settings page.

Your system setup is pretty similar to mine except that I've more RAM. This issue also happens with other people, but I'm still not sure of the cause.

It would really help if someone could run Captura in Direct3D + Direct2D debug modes and let me know if any useful information pops up. My internet right now is not good enough to download the whole Windows SDK.

**Comment by akcansoft** [comment]
I tried `Use GDI instead of Desktop Duplication` setting.
Video recording occurred without error. Thank you.
But there is another problem.
Sounds in video are out of sync. sounds coming much later.

**Comment by MathewSachin** [comment]
Gdi is much slower than Desktop Duplication, so that might be the reason.

Does the audio sync up after a while?

**Comment by akcansoft** [comment]
No. not syc.
Audio: Proximate 5 seconds after the video frame

**Comment by MathewSachin** [comment]
Does the `MF` writer work for you? Try selecting it in place of FFmpeg.

**Comment by akcansoft** [comment]
I tried MF.
But video recorded as flip vertical (top to bottom)
![vlcsnap-2020-03-26-23h13m07s286](https://user-images.githubusercontent.com/7031346/77693100-dbc4e100-6fb8-11ea-8751-3469097bdb8a.png)

**Comment by MathewSachin** [comment]
Hmm... I should be able to fix atleast this flip problem by tomorrow.

Can you try running in DesktopDuplication again with the overlays like Mouse cursor, clicks, keystrokes, etc. disabled.

Also, did you try the SharpAvi writer?

**Comment by akcansoft** [comment]
Ok. 
SharpAvi test:

Settings
![23-48-30](https://user-images.githubusercontent.com/7031346/77695404-c0f46b80-6fbc-11ea-95cd-7b637280528b.png)

Video frame:
![vlcsnap-2020-03-26-23h50m01s935](https://user-images.githubusercontent.com/7031346/77695424-c782e300-6fbc-11ea-8d6f-7ae757cfd708.png)

**Comment by MathewSachin** [comment]
> I tried MF.
But video recorded as flip vertical (top to bottom)

Please try using MF writer with this build:
https://ci.appveyor.com/api/buildjobs/0uldpgmcsqs9sop9/artifacts/temp%2FCaptura-Portable.zip

**Comment by akcansoft** [comment]
MF:  `Use GDI ...` = enabled
again, Video recorded as flip vertical 

MF:  `Use GDI ...` = disabled
![Image1](https://user-images.githubusercontent.com/7031346/77734323-853bbf00-7019-11ea-8d41-d496393bebce.jpg)

**Comment by MathewSachin** [comment]
Click `Copy to clipboard` and paste here.

**Comment by akcansoft** [comment]
Captura v0.0.3502.0
OS: Microsoft Windows 10 Home Single Language|C
64-bit OS
64-bit Process
4 processor(s)

Name: Intel(R) Core(TM) i5 CPU         760  @ 2.80GHz
NumberOfCores: 4
NumberOfLogicalProcessors: 4

Name: Fiziksel Bellek
Capacity: 4294967296

Name: AMD Radeon HD 6800 Series
AdapterRAM: 1073741824

Desktop: {X=0,Y=0,Width=1920,Height=1080}
Screen: \\.\DISPLAY1: {X=0,Y=0,Width=1920,Height=1080}
Mic: Mikrofon (Realtek High Definition Audio)
Speaker: Hoparlör (Realtek High Definition Audio)


SharpDX.SharpDXException: HRESULT: [0xC00D36B1], Module: [Unknown], ApiCode: [Unknown/Unknown], Message: Arabellek istenen eylemi gerçekleştiremeyecek kadar küçük.
   at SharpDX.Result.CheckError()
   at SharpDX.MediaFoundation.SinkWriter.Finalize()
   at DesktopDuplication.MfWriter.Dispose()
   at Captura.Models.WithPreviewWriter.Dispose()
   at Screna.Recorder.<Dispose>d__26.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Threading.ExecutionContext.RunInternal(ExecutionContext executionContext, ContextCallback callback, Object state, Boolean preserveSyncCtx)
   at System.Threading.ExecutionContext.Run(ExecutionContext executionContext, ContextCallback callback, Object state, Boolean preserveSyncCtx)
   at System.Threading.QueueUserWorkItemCallback.System.Threading.IThreadPoolWorkItem.ExecuteWorkItem()
   at System.Threading.ThreadPoolWorkQueue.Dispatch()

**Comment by MathewSachin** [comment]
Were you able to take a video successfully?

> SharpDX.SharpDXException: HRESULT: [0xC00D36B1], Module: [Unknown], ApiCode: [Unknown/Unknown], Message: Arabellek istenen eylemi gerçekleştiremeyecek kadar küçük.

Did this error happen as soon as you started recording or when it ended?

**Comment by Moyf** [comment]
I'm using beta 4, and found that the sound is out of sync, too.
And.. it's very, very slow, like play with 0.5x speed.
