### ISSUE TITLE
crashes while recording video

### ISSUE THREAD

**Issue by vovakms2** [MathewSachin/Captura#548]
application launch - ok
when you try to click - video recording - error (log attached)
similar error also - when in the settings click the "webcam" button
`Captura v9.0.0.0
OS: Майкрософт Windows 10 Pro|C
64-bit OS
64-bit Process
4 processor(s)

Name: Intel(R) Core(TM) i3-2350M CPU @ 2.30GHz
NumberOfCores: 2
NumberOfLogicalProcessors: 4

Name: Физическая память
Capacity: 4294967296

Name: Физическая память
Capacity: 4294967296

Name: Intel(R) HD Graphics 3000
AdapterRAM: 2210398208

Name: NVIDIA GeForce GT 520MX
AdapterRAM: 1073741824

Desktop: {X=0,Y=0,Width=1366,Height=768}
Screen: \\.\DISPLAY1: {X=0,Y=0,Width=1366,Height=768}
Mic: Микрофон (2- Realtek High Definition Audio)
Speaker: Динамики (2- Realtek High Definition Audio)
Webcam: WebCam SC-0311139N

SharpDX.SharpDXException: HRESULT: [0xC00D36B1], Module: [Unknown], ApiCode: [Unknown/Unknown], Message: Буфер слишком мал для выполнения запрошенного действия.
   at SharpDX.Result.CheckError()
   at SharpDX.MediaFoundation.SinkWriter.Finalize()
   at DesktopDuplication.MfWriter.Dispose()
   at Captura.Models.WithPreviewWriter.Dispose()
   at Screna.Recorder.<Dispose>d__25.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Threading.ExecutionContext.RunInternal(ExecutionContext executionContext, ContextCallback callback, Object state, Boolean preserveSyncCtx)
   at System.Threading.ExecutionContext.Run(ExecutionContext executionContext, ContextCallback callback, Object state, Boolean preserveSyncCtx)
   at System.Threading.QueueUserWorkItemCallback.System.Threading.IThreadPoolWorkItem.ExecuteWorkItem()
   at System.Threading.ThreadPoolWorkQueue.Dispatch()`

**Comment by vovakms2** [comment]
application launch - ok
when you try to click - video recording - error (log attached)
similar error also - when in the settings click the "webcam" button
