### ISSUE TITLE
Captura bug

### ISSUE THREAD

**Issue by lishige** [MathewSachin/Captura#573]
Captura v9.0.0.0
OS: Microsoft Windows 10 家庭中文版|C
64-bit OS
64-bit Process
8 processor(s)

Name: Intel(R) Core(TM) i7-8565U CPU @ 1.80GHz
NumberOfCores: 4
NumberOfLogicalProcessors: 8

Name: 物理内存
Capacity: 4294967296

Name: 物理内存
Capacity: 4294967296

Name: Intel(R) UHD Graphics 620
AdapterRAM: 1073741824

Name: NVIDIA GeForce MX250
AdapterRAM: 2147483648

Desktop: {X=0,Y=0,Width=1920,Height=1080}
Screen: \\.\DISPLAY1: {X=0,Y=0,Width=1920,Height=1080}
Mic: 麦克风阵列 (Realtek(R) Audio)
Speaker: 扬声器 (Realtek(R) Audio)
Webcam: USB Video Device

SharpDX.SharpDXException: HRESULT: [0xC00D36B1], Module: [Unknown], ApiCode: [Unknown/Unknown], Message: 缓冲区过小，无法执行请求的操作。
   at SharpDX.Result.CheckError()
   at SharpDX.MediaFoundation.SinkWriter.Finalize()
   at DesktopDuplication.MfWriter.Dispose()
   at Captura.Models.WithPreviewWriter.Dispose()
   at Screna.Recorder.<Dispose>d__25.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Threading.ExecutionContext.RunInternal(ExecutionContext executionContext, ContextCallback callback, Object state, Boolean preserveSyncCtx)
   at System.Threading.ExecutionContext.Run(ExecutionContext executionContext, ContextCallback callback, Object state, Boolean preserveSyncCtx)
   at System.Threading.QueueUserWorkItemCallback.System.Threading.IThreadPoolWorkItem.ExecuteWorkItem()
   at System.Threading.ThreadPoolWorkQueue.Dispatch()

**Comment by lhpitn** [comment]
i guess additional information is needed

is someone able to reproduce that, maybe without this "Home Chinese Edition | C " ( 家庭中文版|C ) ? 

Are the system resources (ram, etc) sufficient?

How often did this occur, able to get some additional stuff (event viewer ( https://learn.microsoft.com/en-us/shows/inside/event-viewer ) , app crash report ( https://www.nirsoft.net/utils/app_crash_view.html ) ) or souch

maybe a dxdiag report ( https://support.cdprojektred.com/en/cyberpunk/pc/sp-technical/issue/637/how-to-create-a-dxdiag-report ) could also be helpfull tu rule out strange graphic hardware/driver thingies

@lishige could you try to provide them?
