### ISSUE TITLE
Console.ReadKey

### ISSUE THREAD

**Issue by avpirogov** [MathewSachin/Captura#86]
When I run Captura.Console app from my GUI app  like this:
```
ProcessStartInfo startInfo = new ProcessStartInfo();
startInfo.UseShellExecute = false;
startInfo.RedirectStandardInput = true;
startInfo.FileName = captureExePath;//captura.exe
startInfo.Arguments = "start --source 100,100,300,400";
process = new Process();
process.StartInfo = startInfo;
process.Start();
```
I get an exption: 
"Cannot read keys when either application does not have a console or when console input has been redirected from a file. Try Console.Read."

```
   at System.Console.ReadKey(Boolean intercept)
   at Captura.Console.Program.Start(MainViewModel ViewModel, StartCmdOptions StartOptions)
   at Captura.Console.Program.<>c.<Main>b__0_0(String verb, Object options)
   at CommandLine.Parser.ParseArguments(String[] args, Object options, Action`2 onVerbCommand)
   at Captura.Console.Program.Main(String[] args)
```

This is caused by line 385 Program.cs: 

`while (ReadKey(true).KeyChar != 'q') ;`

It would be nice to change this block of code for something more "external friendly" :)

```
...
else
            {
                var text = "Press q to quit";

                Write(text);

                while (ReadKey(true).KeyChar != 'q') ;

                Write(new string('\b', text.Length));
            } 
...
```

**Comment by MathewSachin** [comment]
We could rely on `Ctrl + C` to exit using the `Console.CancelKeyPress` event instead of `q`.
Would that be Ok?

**Comment by avpirogov** [comment]
Yes Console.CancelKeyPress should be ok.

**Comment by MathewSachin** [comment]
I've found one problem with using `Ctrl + C` to exit.
It won't be possible to exit the app with input redirected.

A workaround I'm trying is to check the `Console.IsInputRedirected`.
If input is redirected, then `Console.ReadLine` is used instead of `Console.ReadKey`.
So `process.StandardInput.WriteLine('q')` can be used to stop recording.

Working on [fixing-86](https://github.com/MathewSachin/Captura/tree/fixing-86) branch.
Please test, prebuilt: https://ci.appveyor.com/api/buildjobs/6qv4cdykftueqgnl/artifacts/Output%2FCaptura-Release.zip

**Comment by avpirogov** [comment]
Thanks a lot. It works correct. Test case I use:
        
        ```
        Process process;
        public void Start()
        {

            ProcessStartInfo startInfo = new ProcessStartInfo();
            startInfo.UseShellExecute = false;
            startInfo.RedirectStandardInput = true;

            startInfo.FileName = captureExePath;//captura.exe
            startInfo.Arguments = "start --cursor --source 100,100,300,400";
            startInfo.CreateNoWindow = true;

            process = new Process();

            process.StartInfo = startInfo;
            process.Start();

        }

        public void Stop()
        {
            if (process != null)
                process.StandardInput.WriteLine('q');
        }
```

**Comment by avpirogov** [comment]
Deep testing shows new problems ( 
With ffmpeg.exe installed, end "--encoder ffmpeg:0" option I get 0 byte video file.  Test case I use:
        
        ```
        Process process;
        public void Start()
        {

            ProcessStartInfo startInfo = new ProcessStartInfo();
            startInfo.UseShellExecute = false;
            startInfo.RedirectStandardInput = true;

            startInfo.FileName = captureExePath;//captura.exe
            startInfo.Arguments = "start --cursor --source 100,100,300,400 --encoder ffmpeg:0";
            startInfo.CreateNoWindow = true;

            process = new Process();

            process.StartInfo = startInfo;
            process.Start();

        }

        public void Stop()
        {
            if (process != null)
                process.StandardInput.WriteLine('q');
        }
```

**Comment by MathewSachin** [comment]
where is ffmpeg.exe located on your system.
Currently Captura console version loads only from same directory as itself or PATH environment variable.

**Comment by avpirogov** [comment]
Same directory as itself.
dir:
```

19.07.2017  15:21    <DIR>          .
19.07.2017  15:21    <DIR>          ..
18.04.2016  17:02           111 772 bass.dll
24.03.2015  12:50            19 581 bassmix.dll
16.07.2017  10:37           114 176 Captura.Core.dll
16.07.2017  10:37            32 768 captura.exe
16.07.2017  10:37               180 captura.exe.config
16.07.2017  10:37           166 400 Captura.UI.exe
16.07.2017  10:37               861 Captura.UI.exe.config
27.02.2013  09:06            58 368 CommandLine.dll
06.07.2017  16:17        40 924 672 ffmpeg.exe
15.03.2016  10:47           250 368 FirstFloor.ModernUI.dll
08.01.2016  21:37            53 248 Gma.System.MouseKeyHook.dll
02.04.2016  09:02            45 056 Hardcodet.Wpf.TaskbarNotification.dll
17.07.2017  13:30    <DIR>          licenses
22.05.2017  14:55            99 328 ManagedBass.dll
19.05.2017  17:11             9 216 ManagedBass.Mix.dll
17.07.2017  13:30    <DIR>          ml-IN
25.01.2017  18:47           162 304 ModernUI.Xceed.Toolkit.dll
18.06.2017  13:57           653 824 Newtonsoft.Json.dll
03.07.2014  23:20           133 296 Ookii.Dialogs.dll
16.07.2017  10:37            31 744 Screna.dll
10.04.2015  14:45            77 824 SharpAvi.dll
09.06.2017  00:41           454 144 SharpCompress.dll
08.12.2016  22:55           207 872 WebEye.Controls.Wpf.WebCameraControl.dll
13.12.2016  10:48         1 054 720 Xceed.Wpf.Toolkit.dll
```

**Comment by avpirogov** [comment]
Same problem with "--encoder gif". But I get an exception , when trying to stop record with process.StandardInput.WriteLine('q'); :
```
Unhandled Exception: System.AggregateException: One or more errors occurred. ---> System.AggregateException: One or more errors occurred. ---> System.NullReferenceException: Object reference not set to an instance of an object.
   at Captura.ViewModels.MainViewModel.<StartRecording>b__23_0(Exception E)
   at Screna.VFRGifRecorder.Record()
   at System.Threading.Tasks.Task.InnerInvoke()
   at System.Threading.Tasks.Task.Execute()
   --- End of inner exception stack trace ---
   at System.Threading.Tasks.Task.ThrowIfExceptional(Boolean includeTaskCanceledExceptions)
   at System.Threading.Tasks.Task.Wait(Int32 millisecondsTimeout, CancellationToken cancellationToken)
   at Screna.VFRGifRecorder.Dispose(Boolean ErrorOccured)
   at Screna.VFRGifRecorder.Dispose()
   at Captura.ViewModels.MainViewModel.<>c__DisplayClass28_0.<StopRecording>b__0()
   at System.Threading.Tasks.Task.InnerInvoke()
   at System.Threading.Tasks.Task.Execute()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Captura.ViewModels.MainViewModel.<StopRecording>d__28.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Captura.Console.Program.<>c__DisplayClass8_0.<<Start>b__0>d.MoveNext()
   --- End of inner exception stack trace ---
   at System.Threading.Tasks.Task.ThrowIfExceptional(Boolean includeTaskCanceledExceptions)
   at System.Threading.Tasks.Task.Wait(Int32 millisecondsTimeout, CancellationToken cancellationToken)
   at Captura.Console.Program.Start(MainViewModel ViewModel, StartCmdOptions StartOptions)
   at Captura.Console.Program.<>c.<Main>b__0_0(String verb, Object options)
   at CommandLine.Parser.ParseArguments(String[] args, Object options, Action`2 onVerbCommand)
   at Captura.Console.Program.Main(String[] args)
```

**Comment by MathewSachin** [comment]
I verified that the problem with gif is in the ui also. I will try to fix ASAP.

**Comment by MathewSachin** [comment]
Fixed the gif problem. Now, time to check ffmpeg problem.

**Comment by avpirogov** [comment]
Latest [build](https://ci.appveyor.com/project/MathewSachin/captura/build/job/v2y8y2m8hjdx8mu3/artifacts) test  results. In command line, when press q throws exeption:
```
captura.exe start --cursor --encoder ffmpeg:0 --source 255,98,1467,823
Captura v4.2.0
(c) 2017 Mathew Sachin

Press q to quit
Unhandled Exception: System.AggregateException: One or more errors occurred. ---> System.AggregateException: One or more errors occurred. ---> System.NullReferenceException: Object reference not set to an instance of an object.
   at Captura.ViewModels.MainViewModel.<StartRecording>b__23_0(Exception E)
   at Screna.Recorder.DoWrite()
   at System.Threading.Tasks.Task.InnerInvoke()
   at System.Threading.Tasks.Task.Execute()
   --- End of inner exception stack trace ---
   at System.Threading.Tasks.Task.ThrowIfExceptional(Boolean includeTaskCanceledExceptions)
   at System.Threading.Tasks.Task.Wait(Int32 millisecondsTimeout, CancellationToken cancellationToken)
   at Screna.Recorder.Dispose(Boolean TerminateRecord, Boolean TerminateWrite)
   at Screna.Recorder.Dispose()
   at Captura.ViewModels.MainViewModel.<>c__DisplayClass28_0.<StopRecording>b__0()
   at System.Threading.Tasks.Task.InnerInvoke()
   at System.Threading.Tasks.Task.Execute()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Captura.ViewModels.MainViewModel.<StopRecording>d__28.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Captura.Console.Program.<>c__DisplayClass8_0.<<Start>b__0>d.MoveNext()
   --- End of inner exception stack trace ---
   at System.Threading.Tasks.Task.ThrowIfExceptional(Boolean includeTaskCanceledExceptions)
   at System.Threading.Tasks.Task.Wait(Int32 millisecondsTimeout, CancellationToken cancellationToken)
   at Captura.Console.Program.Start(MainViewModel ViewModel, StartCmdOptions StartOptions)
   at Captura.Console.Program.<>c.<Main>b__0_0(String verb, Object options)
   at CommandLine.Parser.ParseArguments(String[] args, Object options, Action`2 onVerbCommand)
   at Captura.Console.Program.Main(String[] args)
```

**Comment by MathewSachin** [comment]
That's I think because the specified region is not within your screen. I think i should change it to intersect with the bounds of the whole screen.

**Comment by MathewSachin** [comment]
Ok. `ffmpeg:0` is `x264`. Now, x264 requires video dimensions to be even. But, the dimensions you specified for height was odd. So, the error occurs. Would fix to automatically make it even as done in the UI.

**Comment by avpirogov** [comment]
Latest commit fixes gif and mpeg problems.
