### ISSUE TITLE
RectangleConverter.ConvertFromString Culture

### ISSUE THREAD

**Issue by avpirogov** [MathewSachin/Captura#87]
When I run "captura shot --source 100,100,300,400" the program stops with exception:

```
Unhandled Exception: System.Exception: 100,100,300,400 is not a valid value for Int32. ---> System.FormatException: Input string was not in a correct format.
   at System.Number.StringToNumber(String str, NumberStyles options, NumberBuffer& number, NumberFormatInfo info, Boolean parseDecimal)
   at System.Number.ParseInt32(String s, NumberStyles style, NumberFormatInfo info)
   at System.ComponentModel.Int32Converter.FromString(String value, NumberFormatInfo formatInfo)
   at System.ComponentModel.BaseNumberConverter.ConvertFrom(ITypeDescriptorContext context, CultureInfo culture, Object value)
   --- End of inner exception stack trace ---
   at System.ComponentModel.BaseNumberConverter.ConvertFrom(ITypeDescriptorContext context, CultureInfo culture, Object value)
   at System.Drawing.RectangleConverter.ConvertFrom(ITypeDescriptorContext context, CultureInfo culture, Object value)
   at Captura.Console.Program.HandleVideoSource(MainViewModel ViewModel, CommonCmdOptions CommonOptions)
   at Captura.Console.Program.Shot(MainViewModel ViewModel, ShotCmdOptions ShotOptions)
   at Captura.Console.Program.<>c.<Main>b__0_0(String verb, Object options)
   at CommandLine.Parser.ParseArguments(String[] args, Object options, Action`2 onVerbCommand)
   at Captura.Console.Program.Main(String[] args)
```

This is caused by culture of my OS, wich is different from en-us. Line 122 MainViewModel.cs:
` var rect = (Rectangle)RectangleConverter.ConvertFromString(Settings.Instance.LastSourceName);`

But I'cant provide corect input because of the limitation "^\d+,\d+,\d+,\d+$" in Program.cs:

```
            if (Regex.IsMatch(CommonOptions.Source, @"^\d+,\d+,\d+,\d+$"))
            {
                var rect = (Rectangle)MainViewModel.RectangleConverter.ConvertFromString(CommonOptions.Source);

                FakeRegionProvider.Instance.SelectedRegion = rect;
                video.SelectedVideoSourceKind = VideoSourceKind.Region;
            }
```

 It would be nice to make RectangleConverter.ConvertFromString(CommonOptions.Source) culture invariant.

**Comment by MathewSachin** [comment]
Please test latest commit.

**Comment by avpirogov** [comment]
For version 4.2.2 still have this problem:

```
C:\Users\x>C:\Captura-Release\captura.exe shot --source 100,100,300,400
Captura v4.2.2
(c) 2017 Mathew Sachin


Unhandled Exception: System.Exception: 100,100,300,400 is not a valid value for Int32. ---> System.FormatException: Input string was not in a correct format.
   at System.Number.StringToNumber(String str, NumberStyles options, NumberBuffer& number, NumberFormatInfo info, Boolean parseDecimal)
   at System.Number.ParseInt32(String s, NumberStyles style, NumberFormatInfo info)
   at System.ComponentModel.Int32Converter.FromString(String value, NumberFormatInfo formatInfo)
   at System.ComponentModel.BaseNumberConverter.ConvertFrom(ITypeDescriptorContext context, CultureInfo culture, Object value)
   --- End of inner exception stack trace ---
   at System.ComponentModel.BaseNumberConverter.ConvertFrom(ITypeDescriptorContext context, CultureInfo culture, Object value)
   at System.Drawing.RectangleConverter.ConvertFrom(ITypeDescriptorContext context, CultureInfo culture, Object value)
   at Captura.Console.Program.HandleVideoSource(MainViewModel ViewModel, CommonCmdOptions CommonOptions)
   at Captura.Console.Program.Shot(MainViewModel ViewModel, ShotCmdOptions ShotOptions)
   at Captura.Console.Program.<>c.<Main>b__0_0(String verb, Object options)
   at CommandLine.Parser.ParseArguments(String[] args, Object options, Action`2 onVerbCommand)
   at Captura.Console.Program.Main(String[] args)
```

**Comment by MathewSachin** [comment]
I'm sorry. I mean't the latest version on the repository.
Anyways, here the prebuilt link: https://ci.appveyor.com/api/buildjobs/dbeen4q5y62lju92/artifacts/Output%2FCaptura-Release.zip

**Comment by avpirogov** [comment]
I'm sorry to. Just download latest commit and build. 
"captura shot --source 100,100,300,400" - works ok for ru-ru Culture. Thanks a lot.
